apiVersion: v1
kind: Service
metadata:
  name: prometheus-elb
  namespace: istio-system
spec:
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
    component: server
    release: prometheus
  sessionAffinity: None
  type: LoadBalancer
