apiVersion: policy.zirain.info/v1alpha1
kind: RateLimit
metadata:
  name: ratelimit-sample
spec:
  workloadSelector:
    app: httpbin
  local:
    rules:
      - match:
          - url:
              matchType: Prefix
              path: "/ip"
        policy:
          brust: 10
          tokensPerFill: 10
          interval: 60s
