apiVersion: policy.zirain.info/v1alpha1
kind: RateLimit
metadata:
  name: ratelimit-sample
spec:
  workloadSelector:
    app: httpbin
  local:
    rules:
      - policy:
          brust: 100
          tokensPerFill: 100
          interval: 60s
      - match:
          - method:
              verb: "GET"
        policy:
          brust: 5
          tokensPerFill: 5
          interval: 60s
