name: CI to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Log in to registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u $ --password-stdin
      - name: Build and push
        id: docker_build
        run: |
          IMG=ghcr.io/zirain/limiter-controller:latest make docker-build
          IMG=ghcr.io/zirain/limiter-controller:latest make docker-push
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
